### ISSUE TITLE
Problème avec les dumps et la concordance

### ISSUE THREAD

**Issue by LeaMondoloni** [LeaMondoloni/PPE1#1]
Dans le script geek fini qui est la correction des exercices, la recherche d'occurrences ne fonctionne pas, le concordancier ne peut donc pas être construit.

**Comment by a-tsioh** [comment]
est-ce que le dossier `./dumps-text` existe bien ? Y-a-t-il des messages d'erreur ? 
(à discuter demain en TP)

**Comment by LeaMondoloni** [comment]
Problème résolu en TP
